apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/etsingh/beard-classifier:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/etsingh/beard-classifier:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: beard-classifier
        chartPath: charts/beard-classifier
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/etsingh/beard-classifier"
          image.tag: "{{.DIGEST_HEX}}"
